#--exclusions----------------------------------------------------------------------

# deployment density
deployment_density: 4 # MW/km²

# exclusion container resolution manual (in meters)
resolution_manual: 1000  # in meters

#landcover codes (buffer in meters) (here landcover codes for openeo as default example)
landcover_codes: #dictionary of landcover code with corresponding buffer in meters
  50: 
  40: 
  70: 
  80: 
  90: 
  95: 
  #10: 1000


#landcover codes (buffer in meters) (here landcover codes for openeo as default example)
#| Code | Class                    |
#| ---- | ------------------------ |
#| 10   | Tree cover               |
#| 20   | Shrubland                |
#| 30   | Grassland                |
#| 40   | Cropland                 |
#| 50   | Built-up                 |
#| 60   | Bare / sparse vegetation |
#| 70   | Snow and ice             |
#| 80   | Permanent water bodies   |
#| 90   | Herbaceous wetland       |
#| 95   | Mangroves                |
#| 100  | Moss and lichen          |

# Below, if you dont want to use some data then insert "null" (without quotation marks). This will skip the file during the exclusion calculation.

# DEM
max_elevation: #meters
max_slope: #degrees
max_terrain_ruggedness: #terrain ruggedness index
max_forest_density: # (0–10 % = non‑forest/scrub, 10–40 % = sparse woodland, 40–70 % = moderately dense forest, >70 % = dense forest).

# spatial elements (buffer in meters)
railways_buffer: 
roads_buffer: 
airports_buffer: 
waterbodies_buffer: 
military_buffer: 
coastlines_buffer: 
protectedAreas_buffer:
transmission_lines_buffer: 
generators_buffer: 
plants_buffer:  

# additional exclusion polygons
additional_exclusion_polygons_buffer: [] #list of buffers in meters in the order of the files in the "additional_exclusion_polygons"-folder in the region data folder

# energy resources
min_wind_speed: 6.5 #m/s
max_wind_speed: null #m/s

# inclusion filter
# EITHER use substations OR transmission OR roads (meters)
substations_inclusion_buffer: 
transmission_inclusion_buffer: 
roads_inclusion_buffer:

# area filter
min_pixels_connected: 5
min_pixels_x: # currently not working, use min_pixels_connected instead
min_pixels_y: # currently not working, use min_pixels_connected instead


# Technology assumptions
turbine:
  default: HW_utility_farm

tech_derate: 0.95

# --Suitability and cost assumptions--------------------------------------------
# Wind resource groups (m/s)
rg_thr: 
    WG1: [6.5, 9.5]
    WG2: [9.5, .inf]