# General
#region parameters.

study_region_name: Beijing 
scenario: new-smk-test
technologies: ['onshorewind'] #onshorewind or solar or offshorewind

#snakemake specific parameters
cores: 4
snakefile: snakemake/Snakefile
weather_years: [2015] #[str(y) for y in range(2010, 2011)]

stages:
  spatial_data_prep: true
  exclusion: true
  suitability: true
  weather_data_prep: true
  weather_bias_adjust: true
  energy_profiles: true

# List of the study-regions in China. 
#         "Anhui", "Beijing", "Chongqing", "Fujian", "Gansu", "Guangdong", "Guangxi", "Guizhou",
#         "Hainan", "Hebei", "Heilongjiang", "Henan", "Hubei", "Hunan", "Jiangsu","Jiangxi",
#         "Jilin", "Liaoning", "West-InnerMongolia", "East-InnerMongolia", "Ningxia", "Qinghai", "Shaanxi", "Shandong", "Shanghai",
#         "Shanxi", "Sichuan", "Tianjin", "Xinjiang", "Xizang", "Yunnan", "Zhejiang" 