#data config 
landcover_source: 'openeo'   #'file' or 'openeo'
consider_railways: 0
consider_roads: 0
consider_airports: 0
consider_waterbodies: 0
consider_additional_exclusion_polygons: 0 
EPSG_manual: ''  #if None use empty string


#Define study region (use geopackage from gadm.org to inspect in QGIS)
region_name: Elbe-Elster #always needed, same name as in gadm.org (if country is studied, then use country name)
OSM_folder_name: BerlinBrandenburg #usually same as country_code, only needed if OSM is to be considered


#use GADM boundary
country_code: DEU #    #PRT  #St√§dteregion Aachen in level 2 #Porto in level 1 #Elbe-Elster in level 2 #Zell am See in level 2
gadm_level: 2
#or use custom region
custom_polygon_filename: '' #if None use empty string           'Aceh_single.geojson'


#north facing pixels to be excluded (pixels with slope bigger X and aspect between Y and Z)
X: 10
Y: 310
Z: 50