#data config 
landcover_source: 'openeo'   #'file' or 'openeo'
consider_coastlines: 0
consider_railways: 0
consider_roads: 0
consider_airports: 0
consider_waterbodies: 0

consider_additional_exclusion_polygons: 0 

consider_WDPA: 0
wdpa_url: 'https://d1gam3xoknrgr2.cloudfront.net/current/WDPA_WDOECM_Nov2024_Public_DEU.zip'


EPSG_manual: ''  #if None use empty string


#name folders and files
region_folder_name: Elbe-Elster #always needed, same name as in gadm.org (if country is studied, then use country name)
OSM_folder_name: BerlinBrandenburg #usually same as country_code, only needed if OSM is to be considered

DEM_filename: gebco_cutout.tif 
landcover_filename: PROBAV_LC100_global_v3.0.1_2019-nrt_Discrete-Classification-map_EPSG-4326.tif


#Define study region (use geopackage from gadm.org to inspect in QGIS or go on gadm.org)
#use GADM boundary (https://gadm.org/maps.html)
region_name: Elbe-Elster
country_code: DEU 
gadm_level: 2
#or use custom region (if file is passed, then this is used as default over the GADM definitions above)
custom_polygon_filename: '' #if None use empty string


#north facing pixels to be excluded (pixels with slope bigger X and aspect between Y and Z)
X: 10
Y: 310
Z: 50


#world database of protected areas
wdpa_consider_status: ["Adopted", "Designated", "Established", "Inscribed"] #all possibilies: "Adopted", "Designated", "Established", "Inscribed", "Proposed"