#--exclusions----------------------------------------------------------------------
# scenario name (written in available area filename)
scenario: 'ref'

# deployment density
deployment_density: 50 # MW/kmÂ²

# resolution manual
resolution_manual: 

#landcover codes (buffer in meters) (here landcover codes for openeo as default example)
landcover_without_buffer: [10,40,70,80,90] #list of landcover codes
landcover_with_buffer: #dictionary of landcover code with corresponding buffer in meters
  50: 2000 #built-up land with 2000m buffer 

# Below, if you dont want to use some data then insert "null" (without quotation marks). This will skip the file during the exclusion calculation.

# DEM
max_elevation: 2000 #meters
max_slope: 20 #degrees

# spatial elements (buffer in meters)
railways_buffer: 50
roads_buffer: 50
airports_buffer: 5000
waterbodies_buffer: 20
military_buffer: 100
coastlines_buffer: 200
protectedAreas_buffer: 50
transmission_lines_buffer: 100

# additional exclusion polygons
additional_exclusion_polygons_buffer: [] #list of buffers in meters in the order of the files in the "additional_exclusion_polygons"-folder in the region data folder

# solar and wind resources
min_wind_speed: 0
max_wind_speed: 15

min_solar_production: 0
max_solar_production: 5000

transmission_buffer: 100 #buffer in meters for transmission lines, if None then no buffer is applied

# inclusion filter
# EITHER use substations OR transmission (meters)
substations_inclusion_buffer: 10000
transmission_inclusion_buffer: 10000

# area filter
min_pixels_connected: 5
min_pixels_x: # currently not working, use min_pixels_connected instead
min_pixels_y: # currently not working, use min_pixels_connected instead

# model areas 
model_areas_filename:

# Technology assumptions
windturbine_onshore: 'LW_farm.yaml'
tech_derate: 0.95

# --Suitability and cost assumptions--------------------------------------------
# Wind resource groups (m/s)
wg_thr: 
    WG1: [3.5, 4.5] 
    WG2: [4.5, 5.5]
    WG3: [5.5, 6.5]
    WG4: [6.5, 7.5]
    WG5: [7.5, 30]
