# General
#region parameters.

study_region_name: Beijing
scenario: ref
technologies: ["onshorewind"]

#snakemake specific parameters
cores: 4
snakefile: snakemake/Snakefile
weather_years: [2015, 2020] #[str(y) for y in range(2010, 2011)]

stages:
  spatial_data_prep: true
  exclusion: true
  suitability: true
  weather_data_prep: true
  weather_bias_adjust: true
  energy_profiles: true