#--exclusions----------------------------------------------------------------------

# deployment density
deployment_density: 50 # MW/km²

# exclusion container resolution manual
resolution_manual: null

#landcover codes (buffer in meters) (here landcover codes for openeo as default example)
landcover_codes: #dictionary of landcover code with corresponding buffer in meters
  50: 500
  70: 0

#landcover codes (buffer in meters) (here landcover codes for openeo as default example)
#| Code | Class                    |
#| ---- | ------------------------ |
#| 10   | Tree cover               |
#| 20   | Shrubland                |
#| 30   | Grassland                |
#| 40   | Cropland                 |
#| 50   | Built-up                 |
#| 60   | Bare / sparse vegetation |
#| 70   | Snow and ice             |
#| 80   | Permanent water bodies   |
#| 90   | Herbaceous wetland       |
#| 95   | Mangroves                |
#| 100  | Moss and lichen          |

# Below, if you dont want to use some data then insert "null" (without quotation marks). This will skip the file during the exclusion calculation.

# DEM
max_elevation: 2000 #meters
max_slope: 15 #degrees
max_terrain_ruggedness: Null #terrain ruggedness index

# spatial elements (buffer in meters)
railways_buffer: 100
roads_buffer: 100
airports_buffer: 5000
waterbodies_buffer: 50
military_buffer: 500
coastlines_buffer: 500
protectedAreas_buffer: 0
transmission_lines_buffer: 100
generators_buffer: 100
plants_buffer: 100 

# additional exclusion rasters
max_forest_density: null # (0–10 % = non‑forest/scrub, 10–40 % = sparse woodland, 40–70 % = moderately dense forest, >70 % = dense forest).

# additional exclusion polygons
additional_exclusion_polygons_buffer: [] #list of buffers in meters in the order of the files in the "additional_exclusion_polygons"-folder in the region data folder

# energy resources
min_solar_production: 1000 #kWh/kW/year
max_solar_production: null #kWh/kW/year

# inclusion filters (connected with AND logic) (meters)
substations_inclusion_buffer: null
transmission_inclusion_buffer: 10000
roads_inclusion_buffer: null

# area filter
min_pixels_connected: 5
min_pixels_x: # currently not working, use min_pixels_connected instead
min_pixels_y: # currently not working, use min_pixels_connected instead


# -- timeseries assumptions---------------------------------------------
# Technology assumptions
panel: 'CSi.yaml'

tech_derate: 0.95

# --Suitability and cost assumptions--------------------------------------------
# Solar resource groups (kWh/m²/year)
rg_thr: 
    SG1: [1000, 1300]
    SG2: [1300, 1600]
    SG3: [1600, 3000]
